---
name: Generation Check

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/gencheck.yaml'
      - '**.go'

concurrency:
  group: 'gencheck-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  gencheck:
    runs-on: [custom, linux, large]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make gencheck
  save-artifacts-on-fail:
    if: ${{ needs.gencheck.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
